### ISSUE TITLE
Move the "kubernetes" package from "internal" to "pkg" or something else

### ISSUE THREAD

**Issue by alexandrevilain** [chuckha/kubeyaml#3]
Hi!

Thanks for this project, it's petty cool!

Your package `internal/kubernetes` looks pretty useful for many tools. As it's in the `internal` package it can't be imported in another project. 

In order to make it available for others projects, can we move it to another package such as `pkg/kubernetes` or event at the project's root?

I can do a PR for that if you want :) 

Thanks!

**Comment by chuckha** [comment]
I appreciate the request but this code was not written as a library for external supporters. That can end up being a lot of work. I don't want to dive too quickly into this. Do you have a specific use case you're thinking of? Or perhaps an example project that could use the `internal/kubernetes` package?

**Comment by alexandrevilain** [comment]
My idea was to build a kubectl plugin to add a `lint` or `validate` feature to kubectl using your kubernetes package.
But, no problem, I'll build my own!
